#!/usr/bin/env bash
#
# SCRIPT: install-dotfiles
# AUTHOR: Hogan Lee
#
# PLATFORM: Mac OS X
#
# REQUIREMENTS: None
#
# PURPOSE: This script creates symlinks and copies files from this dotfiles
#          directory into $HOME.
#
# set -n   # Uncomment to check script syntax, without execution.
#          # NOTE: Do not forget to put the # comment back in or
#          #       the shell script will never execute!
# set -x   # Uncomment to debug this shell script
#
##########################################################
#         DEFINE fileS AND VARIABLES HERE
##########################################################

# Directory where this script was called from
dotfiles_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Old dotfiles backup directory
dotfiles_old="$(dirname $dotfiles_dir)/dotfiles_old"

# Files/folders to symlink into home directory
home_dir_symlinks="bashrc bash_profile"

# Better to copy some files instead of symlinking them
files_to_copy="gitconfig"


##########################################################
#              DEFINE FUNCTIONS HERE
##########################################################

# Thanks Paul Irish
# https://github.com/paulirish/dotfiles/blob/master/symlink-setup.sh
print_success () {
    printf "\e[1;36m  [✔] $1\e[0m\n"
}

##########################################################
#               BEGINNING OF MAIN
##########################################################

# Check for existing ~/.dotfiles symlink first
if [[ -h ~/.dotfiles ]] && [[ -d ~/.dotfiles ]]; then
  echo
  rm ~/.dotfiles
  print_success "Found existing ~/.dotfiles symlink. Deleted it."
fi

# Symlink this project folder to ~
# This is the most important step!
ln -s "$dotfiles_dir" ~/.dotfiles

# Create `dotfiles_old` to place backups into
if [[ -d "$dotfiles_old" ]]; then
  echo
  print_success "$dotfiles_old already exists. Deleted it."

  rm -rf "$dotfiles_old"
fi

echo
mkdir "$dotfiles_old" &&
print_success "Created '$dotfiles_old' \to backup any existing dotfiles in ~\n"

# Move any existing dotfiles in ~ to dotfiles_old directory, then create
# symlinks
for file in $home_dir_symlinks; do
    if [ -e ~/.$file ]; then
        mv ~/."$file" "$dotfiles_old" &&
        print_success "Moved existing .$file from ~ to $dotfiles_old\n"
    fi
    ln -s "$dotfiles_dir"/"$file" ~/."$file" &&
    print_success "Created symlink to $file in ~.\n"
done

# Move any existing dotfiles in ~ to dotfiles_old directory, then copy files
for file in $files_to_copy; do
    if [ -e ~/.$file ]; then
        mv ~/."$file" "$dotfiles_old" &&
        print_success "Moved existing .$file from ~ to $dotfiles_old\n"
    fi
    cp "$dotfiles_dir"/"$file" ~/."$file" &&
    print_success "Copied $file to home directory.\n"
done

# Source .bash_profile again
source ~/.bash_profile
print_success "Sourced your ~/.bash_profile again. That's it, everything's setup!\n"

# End of script
