#!/usr/bin/env bash
#
# SCRIPT: install-dotfiles
# AUTHOR: Hogan Lee
#
# PLATFORM: Mac OS X
#
# REQUIREMENTS: None
#
# PURPOSE: This script creates symlinks and copies files from this dotfiles
#          directory into $HOME.
#
# set -n   # Uncomment to check script syntax, without execution.
#          # NOTE: Do not forget to put the # comment back in or
#          #       the shell script will never execute!
# set -x   # Uncomment to debug this shell script
#
##########################################################
#         DEFINE fileS AND VARIABLES HERE
##########################################################

# Directory where this script was called from
dotfiles_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Old dotfiles backup directory
dotfiles_old="$(dirname $dotfiles_dir)/dotfiles_old"

# Files/folders to symlink into home directory
home_dir_symlinks="bashrc bash_profile"

# Better to copy some files instead of symlinking them
files_to_copy="gitconfig"


##########################################################
#              DEFINE FUNCTIONS HERE
##########################################################


##########################################################
#               BEGINNING OF MAIN
##########################################################

# Check for existing ~/.dotfiles symlink first
if [[ -h ~/.dotfiles ]] && [[ -d ~/.dotfiles ]]; then
  echo
  echo "Found existing ~/.dotfiles symlink. Removing it first..."
  rm ~/.dotfiles
fi

# Symlink this project folder to ~
ln -s "$dotfiles_dir" ~/.dotfiles

# Create `dotfiles_old` to place backups into
if [[ -d "$dotfiles_old" ]]; then
  echo
  echo "$dotfiles_old already exists. Removing first..."

  rm -rf "$dotfiles_old"
fi

printf "Creating '%s' for backup of any existing dotfiles in ~\n" $dotfiles_old
mkdir "$dotfiles_old"
printf "...done\n\n"

# Move any existing dotfiles in ~ to dotfiles_old directory, then create
# symlinks
for file in $home_dir_symlinks; do
    if [ -e ~/.$file ]; then
        printf "Moving existing .%s from ~ to %s\n" $file $dotfiles_old
        mv ~/."$file" "$dotfiles_old"
    fi
    printf "Creating symlink to %s in ~.\n\n" $file
    ln -s "$dotfiles_dir"/"$file" ~/."$file"
done

# Move any existing dotfiles in ~ to dotfiles_old directory, then copy files
for file in $files_to_copy; do
    if [ -e ~/.$file ]; then
        printf "Moving existing .%s from ~ to %s\n" $file $dotfiles_old
        mv ~/."$file" "$dotfiles_old"
    fi
    printf "Copying %s to home directory.\n\n" $file
    cp "$dotfiles_dir"/"$file" ~/."$file"
done

# Source .bash_profile again
echo "Sourcing your ~/.bash_profile again. That's it, everything's setup!"
echo
. ~/.bash_profile

# End of script
